-- v4.4.0 native governed software delivery graph.  All objects are additive.
-- APPROVED_BASELINE records are immutable; EXPECTED_VERSION fences patches.
CREATE TABLE IF NOT EXISTS spec_versions (version_id varchar(128) PRIMARY KEY,spec_id varchar(128) NOT NULL,version_number bigint NOT NULL,change_type varchar(64) NOT NULL,change_summary varchar(2000),diff_json text NOT NULL DEFAULT '{}',created_by varchar(256),created_at timestamp NOT NULL DEFAULT current_timestamp,UNIQUE(spec_id,version_number));
CREATE TABLE IF NOT EXISTS cx_sdd_changes (change_id varchar(128) PRIMARY KEY,title varchar(512) NOT NULL,summary text,profile_key varchar(64) NOT NULL,security_domain_id varchar(128),status varchar(32) NOT NULL,current_revision_id varchar(128),created_by varchar(256) NOT NULL,updated_by varchar(256) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp,updated_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_sdd_source_snapshots (snapshot_id varchar(128) PRIMARY KEY,change_id varchar(128) NOT NULL,source_format varchar(32) NOT NULL,content_json text NOT NULL,content_digest varchar(64) NOT NULL,created_by varchar(256) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp,UNIQUE(change_id,content_digest));
CREATE TABLE IF NOT EXISTS cx_sdd_revisions (revision_id varchar(128) PRIMARY KEY,change_id varchar(128) NOT NULL,revision_no bigint NOT NULL,revision_state varchar(32) NOT NULL,source_kind varchar(32) NOT NULL,source_snapshot_id varchar(128),content_digest varchar(64) NOT NULL,expected_version bigint NOT NULL DEFAULT 1,baseline_of_revision_id varchar(128),approved_by varchar(256),approved_at timestamp,created_by varchar(256) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp,reason varchar(2000),UNIQUE(change_id,revision_no));
CREATE TABLE IF NOT EXISTS cx_sdd_clauses (clause_id varchar(128) PRIMARY KEY,revision_id varchar(128) NOT NULL,clause_kind varchar(64) NOT NULL,clause_key varchar(128) NOT NULL,title varchar(1000) NOT NULL,body_text text,structured_json text NOT NULL DEFAULT '{}',status varchar(32) NOT NULL,ordinal bigint NOT NULL DEFAULT 0,expected_version bigint NOT NULL DEFAULT 1,created_by varchar(256) NOT NULL,updated_by varchar(256) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp,updated_at timestamp NOT NULL DEFAULT current_timestamp,UNIQUE(revision_id,clause_key));
CREATE TABLE IF NOT EXISTS cx_sdd_unresolved_fragments (fragment_id varchar(128) PRIMARY KEY,revision_id varchar(128) NOT NULL,fragment_kind varchar(64) NOT NULL,source_path varchar(1024),source_offset bigint,content_digest varchar(64) NOT NULL,summary text,status varchar(32) NOT NULL,waived_by varchar(256),waiver_reason varchar(2000),waiver_expires_at timestamp,created_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_sdd_tasks (task_id varchar(128) PRIMARY KEY,revision_id varchar(128) NOT NULL,title varchar(1000) NOT NULL,role_key varchar(64) NOT NULL,risk_level varchar(16) NOT NULL,read_set_json text NOT NULL DEFAULT '[]',write_set_json text NOT NULL DEFAULT '[]',depends_on_json text NOT NULL DEFAULT '[]',status varchar(32) NOT NULL,assigned_principal_id varchar(256),expected_version bigint NOT NULL DEFAULT 1,created_by varchar(256) NOT NULL,updated_by varchar(256) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp,updated_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_sdd_resource_leases (lease_id varchar(128) PRIMARY KEY,run_id varchar(128),task_id varchar(128) NOT NULL,resource_kind varchar(64) NOT NULL,resource_ref varchar(2048) NOT NULL,owner_principal_id varchar(256) NOT NULL,fencing_token bigint NOT NULL DEFAULT 1,status varchar(32) NOT NULL,lease_expires_at timestamp NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp,updated_at timestamp NOT NULL DEFAULT current_timestamp,UNIQUE(resource_kind,resource_ref,status));
CREATE TABLE IF NOT EXISTS cx_sdd_runs (run_id varchar(128) PRIMARY KEY,revision_id varchar(128) NOT NULL,graph_version_id varchar(128),status varchar(32) NOT NULL,risk_level varchar(16) NOT NULL DEFAULT 'LOW',budget_json text NOT NULL DEFAULT '{}',context_digest varchar(64),created_by varchar(256) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp,updated_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_sdd_run_nodes (run_node_id varchar(128) PRIMARY KEY,run_id varchar(128) NOT NULL,task_id varchar(128),node_key varchar(256) NOT NULL,status varchar(32) NOT NULL,read_set_json text NOT NULL DEFAULT '[]',write_set_json text NOT NULL DEFAULT '[]',checkpoint_digest varchar(64),created_at timestamp NOT NULL DEFAULT current_timestamp,updated_at timestamp NOT NULL DEFAULT current_timestamp,UNIQUE(run_id,node_key));
CREATE TABLE IF NOT EXISTS cx_sdd_evidence (evidence_id varchar(128) PRIMARY KEY,revision_id varchar(128) NOT NULL,task_id varchar(128),criterion_clause_id varchar(128),evidence_type varchar(64) NOT NULL,source_kind varchar(64) NOT NULL,reference_uri varchar(2048),artifact_digest varchar(128) NOT NULL,detail_json text NOT NULL DEFAULT '{}',independent_flag char(1) NOT NULL DEFAULT 'N',status varchar(32) NOT NULL,created_by varchar(256) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_sdd_reviews (review_id varchar(128) PRIMARY KEY,revision_id varchar(128) NOT NULL,task_id varchar(128),review_kind varchar(64) NOT NULL,status varchar(32) NOT NULL,reviewer_principal_id varchar(256),decision_reason varchar(2000),created_at timestamp NOT NULL DEFAULT current_timestamp,decided_at timestamp);
CREATE TABLE IF NOT EXISTS cx_sdd_gates (gate_id varchar(128) PRIMARY KEY,run_id varchar(128) NOT NULL,gate_kind varchar(64) NOT NULL,status varchar(32) NOT NULL,risk_level varchar(16) NOT NULL,impact_json text NOT NULL DEFAULT '{}',decision varchar(32),decision_reason varchar(2000),created_by varchar(256) NOT NULL,decided_by varchar(256),created_at timestamp NOT NULL DEFAULT current_timestamp,decided_at timestamp);
CREATE TABLE IF NOT EXISTS cx_sdd_scm_connections (connection_id varchar(128) PRIMARY KEY,adapter_kind varchar(32) NOT NULL,repository_ref varchar(2048) NOT NULL,credential_reference varchar(512),policy_json text NOT NULL DEFAULT '{}',status varchar(32) NOT NULL,created_by varchar(256) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp,updated_at timestamp NOT NULL DEFAULT current_timestamp,UNIQUE(adapter_kind,repository_ref));
CREATE TABLE IF NOT EXISTS cx_sdd_artifacts (artifact_id varchar(128) PRIMARY KEY,run_id varchar(128),task_id varchar(128),artifact_kind varchar(64) NOT NULL,reference_uri varchar(2048) NOT NULL,content_digest varchar(128) NOT NULL,status varchar(32) NOT NULL,created_by varchar(256) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp,UNIQUE(reference_uri,content_digest));
CREATE INDEX IF NOT EXISTS idx_sdd_change_status ON cx_sdd_changes(status,updated_at);
CREATE INDEX IF NOT EXISTS idx_sdd_revision_state ON cx_sdd_revisions(change_id,revision_state);
CREATE INDEX IF NOT EXISTS idx_sdd_task_status ON cx_sdd_tasks(revision_id,status);
CREATE INDEX IF NOT EXISTS idx_sdd_evidence_rev ON cx_sdd_evidence(revision_id,status);
INSERT INTO cx_platform_capabilities(capability_key,mandatory) VALUES ('native_sdd_control_plane','Y'),('governed_sdd_execution','Y'),('software_delivery_profile','Y'),('sdd_workbench','Y'),('scm_execution_adapters','N') ON CONFLICT (capability_key) DO NOTHING;
