-- v4.4.1 Platform Administration, Admin Agent HA, upgrade and containment.
-- Secrets are never stored here; only digests or encrypted references are kept.
CREATE TABLE IF NOT EXISTS cx_admin_agent_groups (group_id varchar(128) PRIMARY KEY, group_key varchar(128) NOT NULL UNIQUE, status varchar(32) NOT NULL DEFAULT 'ACTIVE', production_policy char(1) NOT NULL DEFAULT 'Y', current_term bigint NOT NULL DEFAULT 0, leader_member_id varchar(128), leader_lease_expires_at timestamp, fencing_token bigint NOT NULL DEFAULT 0, configuration_state varchar(32) NOT NULL DEFAULT 'VALID', created_at timestamp NOT NULL DEFAULT current_timestamp, updated_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_admin_agent_members (member_id varchar(128) PRIMARY KEY, group_id varchar(128) NOT NULL, agent_id varchar(128) NOT NULL, admission_path varchar(32) NOT NULL, status varchar(32) NOT NULL DEFAULT 'CANDIDATE', voting_enabled char(1) NOT NULL DEFAULT 'N', weight bigint NOT NULL DEFAULT 1, node_id varchar(256), public_key_digest varchar(128), candidate_since timestamp NOT NULL DEFAULT current_timestamp, approved_at timestamp, updated_at timestamp NOT NULL DEFAULT current_timestamp, UNIQUE(group_id, agent_id));
CREATE TABLE IF NOT EXISTS cx_admin_enrollments (enrollment_id varchar(128) PRIMARY KEY, group_id varchar(128), admission_path varchar(32) NOT NULL, agent_id varchar(128), node_id varchar(256), public_key_digest varchar(128) NOT NULL, package_digest varchar(128) NOT NULL, status varchar(32) NOT NULL DEFAULT 'CANDIDATE', reason varchar(2000) NOT NULL, requested_by varchar(128) NOT NULL, expires_at timestamp NOT NULL, approved_by varchar(128), created_at timestamp NOT NULL DEFAULT current_timestamp, updated_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_admin_quorum_snapshots (snapshot_id varchar(128) PRIMARY KEY, group_id varchar(128) NOT NULL, term bigint NOT NULL, members_json text NOT NULL, total_weight bigint NOT NULL, required_count bigint NOT NULL, required_weight bigint NOT NULL, decision varchar(32), decision_reason varchar(2000), created_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_admin_leader_evidence (evidence_id varchar(128) PRIMARY KEY, group_id varchar(128) NOT NULL, member_id varchar(128) NOT NULL, old_term bigint, new_term bigint NOT NULL, old_fencing_token bigint, new_fencing_token bigint NOT NULL, event_type varchar(64) NOT NULL, detail_json text NOT NULL DEFAULT '{}', created_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_management_artifacts (artifact_id varchar(128) PRIMARY KEY, artifact_key varchar(256) NOT NULL, artifact_version varchar(64) NOT NULL, artifact_kind varchar(64) NOT NULL, content_digest varchar(128) NOT NULL, signature varchar(2048) NOT NULL, classification varchar(32) NOT NULL DEFAULT 'INTERNAL', secret_free char(1) NOT NULL DEFAULT 'Y', status varchar(32) NOT NULL DEFAULT 'PUBLISHED', storage_adapter varchar(32) NOT NULL DEFAULT 'PEER', created_by varchar(128) NOT NULL, created_at timestamp NOT NULL DEFAULT current_timestamp, UNIQUE(artifact_key, artifact_version));
CREATE TABLE IF NOT EXISTS cx_management_artifact_receipts (receipt_id varchar(128) PRIMARY KEY, artifact_id varchar(128) NOT NULL, node_id varchar(256) NOT NULL, received_digest varchar(128), signature_state varchar(32) NOT NULL DEFAULT 'PENDING', availability_state varchar(32) NOT NULL DEFAULT 'MISSING', detail_json text NOT NULL DEFAULT '{}', received_at timestamp, updated_at timestamp NOT NULL DEFAULT current_timestamp, UNIQUE(artifact_id,node_id));
CREATE TABLE IF NOT EXISTS cx_upgrade_plans (upgrade_id varchar(128) PRIMARY KEY, package_version varchar(64) NOT NULL, edition varchar(32) NOT NULL, package_digest varchar(128) NOT NULL, signature_state varchar(32) NOT NULL DEFAULT 'PENDING', preflight_state varchar(32) NOT NULL DEFAULT 'PENDING', approval_state varchar(32) NOT NULL DEFAULT 'PENDING', rollout_state varchar(32) NOT NULL DEFAULT 'PENDING', status varchar(32) NOT NULL DEFAULT 'STAGED', reason varchar(2000) NOT NULL, created_by varchar(128) NOT NULL, created_at timestamp NOT NULL DEFAULT current_timestamp, updated_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_upgrade_nodes (upgrade_node_id varchar(128) PRIMARY KEY, upgrade_id varchar(128) NOT NULL, node_id varchar(256) NOT NULL, state varchar(32) NOT NULL DEFAULT 'PENDING', active_work_count bigint NOT NULL DEFAULT 0, old_version varchar(64), new_version varchar(64), skill_state varchar(32) NOT NULL DEFAULT 'UNCHANGED', health_state varchar(32) NOT NULL DEFAULT 'UNKNOWN', evidence_json text NOT NULL DEFAULT '{}', updated_at timestamp NOT NULL DEFAULT current_timestamp, UNIQUE(upgrade_id,node_id));
CREATE TABLE IF NOT EXISTS cx_skill_distribution (distribution_id varchar(128) PRIMARY KEY, upgrade_id varchar(128) NOT NULL, agent_id varchar(128) NOT NULL, skill_version varchar(64) NOT NULL, message_state varchar(32) NOT NULL DEFAULT 'PENDING', acknowledgement_state varchar(32) NOT NULL DEFAULT 'PENDING', activation_state varchar(32) NOT NULL DEFAULT 'OLD_VERSION', drift_state varchar(32) NOT NULL DEFAULT 'UNKNOWN', evidence_json text NOT NULL DEFAULT '{}', updated_at timestamp NOT NULL DEFAULT current_timestamp, UNIQUE(upgrade_id,agent_id,skill_version));
CREATE TABLE IF NOT EXISTS cx_agent_containment_commands (command_id varchar(128) PRIMARY KEY, agent_id varchar(128) NOT NULL, instance_id varchar(128) NOT NULL, requested_state varchar(32) NOT NULL, control_generation bigint NOT NULL, nonce_digest varchar(128) NOT NULL, issuer_principal_id varchar(128) NOT NULL, reason varchar(2000) NOT NULL, expires_at timestamp NOT NULL, signature varchar(2048) NOT NULL, authority_state varchar(32) NOT NULL DEFAULT 'PENDING', agent_ack_state varchar(32) NOT NULL DEFAULT 'PENDING', infrastructure_ack_state varchar(32) NOT NULL DEFAULT 'NOT_CONFIGURED', cleanup_evidence_json text NOT NULL DEFAULT '{}', created_at timestamp NOT NULL DEFAULT current_timestamp, updated_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_web_session_policies (policy_key varchar(32) PRIMARY KEY, idle_timeout_seconds bigint NOT NULL, absolute_timeout_seconds bigint NOT NULL, version bigint NOT NULL DEFAULT 1, updated_by varchar(128) NOT NULL, reason varchar(2000) NOT NULL, updated_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_web_session_policy_history (history_id varchar(128) PRIMARY KEY, policy_key varchar(32) NOT NULL, version bigint NOT NULL, idle_timeout_seconds bigint NOT NULL, absolute_timeout_seconds bigint NOT NULL, changed_by varchar(128) NOT NULL, reason varchar(2000) NOT NULL, created_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_api_cursors (cursor_id varchar(128) PRIMARY KEY, principal_id varchar(128) NOT NULL, resource_key varchar(64) NOT NULL, filter_digest varchar(128) NOT NULL, sort_key varchar(256) NOT NULL, page_size bigint NOT NULL, position_key varchar(256), expires_at timestamp NOT NULL, created_at timestamp NOT NULL DEFAULT current_timestamp);
ALTER TABLE cx_admin_enrollments ADD COLUMN IF NOT EXISTS requested_by varchar(128);
UPDATE cx_admin_enrollments SET requested_by = 'SYSTEM_LEGACY' WHERE requested_by IS NULL;
ALTER TABLE cx_admin_enrollments ALTER COLUMN requested_by SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_cx_admin_member_group ON cx_admin_agent_members(group_id,status,voting_enabled,weight);
CREATE INDEX IF NOT EXISTS idx_cx_containment_instance ON cx_agent_containment_commands(instance_id,control_generation,authority_state);
CREATE INDEX IF NOT EXISTS idx_cx_upgrade_nodes ON cx_upgrade_nodes(upgrade_id,state,node_id);
INSERT INTO cx_platform_capabilities(capability_key,mandatory,enabled) VALUES ('admin_channel_ha','Y','Y'),('controlled_upgrade','Y','Y'),('agent_containment','Y','Y'),('session_policy','Y','Y') ON CONFLICT (capability_key) DO NOTHING;
