-- v4.4.4 governed Portal Agent Pool, managed nodes, storage and endpoints.
CREATE TABLE IF NOT EXISTS cx_portal_llm_policies (policy_id varchar(64) PRIMARY KEY,default_profile_id varchar(128),version bigint NOT NULL DEFAULT 1,updated_by varchar(128),reason varchar(2000),updated_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_portal_llm_allowlist (policy_id varchar(64) NOT NULL,profile_id varchar(128) NOT NULL,status varchar(32) NOT NULL DEFAULT 'ACTIVE',updated_by varchar(128),reason varchar(2000),updated_at timestamp NOT NULL DEFAULT current_timestamp,PRIMARY KEY(policy_id,profile_id));
CREATE TABLE IF NOT EXISTS cx_platform_admin_commands (command_id varchar(128) PRIMARY KEY,command_type varchar(64) NOT NULL,target_json text NOT NULL,parameters_json text NOT NULL,security_domain_id varchar(128) NOT NULL,requested_by varchar(128) NOT NULL,reason varchar(2000) NOT NULL,status varchar(32) NOT NULL,expires_at timestamp NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp,updated_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_managed_nodes (node_id varchar(128) PRIMARY KEY,node_key varchar(128) UNIQUE NOT NULL,host_reference varchar(256) NOT NULL,ssh_port integer NOT NULL DEFAULT 22,os_user varchar(128),role_json text NOT NULL,failure_domain varchar(128),trust_mode varchar(32) NOT NULL,status varchar(32) NOT NULL,validation_state varchar(32) NOT NULL,created_by varchar(128) NOT NULL,reason varchar(2000) NOT NULL,last_validated_at timestamp,created_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_shared_storage_profiles (storage_id varchar(128) PRIMARY KEY,storage_key varchar(128) UNIQUE NOT NULL,backend_kind varchar(32) NOT NULL,location_ref varchar(512) NOT NULL,status varchar(32) NOT NULL,validation_state varchar(32) NOT NULL,created_by varchar(128) NOT NULL,reason varchar(2000) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE TABLE IF NOT EXISTS cx_external_db_endpoints (endpoint_id varchar(128) PRIMARY KEY,endpoint_key varchar(128) UNIQUE NOT NULL,database_dialect varchar(32) NOT NULL,host_reference varchar(256) NOT NULL,port integer NOT NULL,tls_required varchar(1) NOT NULL DEFAULT 'Y',status varchar(32) NOT NULL,created_by varchar(128) NOT NULL,reason varchar(2000) NOT NULL,created_at timestamp NOT NULL DEFAULT current_timestamp);
CREATE INDEX IF NOT EXISTS idx_cx_admin_command_status ON cx_platform_admin_commands(status,created_at);
CREATE INDEX IF NOT EXISTS idx_cx_managed_node_role ON cx_managed_nodes(status,validation_state);
INSERT INTO cx_portal_llm_policies(policy_id,version,updated_by,reason) VALUES ('DEFAULT',1,'SYSTEM','v4.4.4 Portal Agent Pool default policy') ON CONFLICT (policy_id) DO NOTHING;
INSERT INTO cx_agent_templates(template_id,template_key,display_name,template_kind,content_json,content_digest,locked_fields_json,status,managed,created_by)
VALUES ('TPL_CODE_PLAN','CODE_PLAN','Code Planning Agent','BUSINESS','{"skills":["task-plan","specs"],"classification":"INTERNAL"}','v4.4.4-code-plan','["skills","classification"]','PUBLISHED','Y','SYSTEM') ON CONFLICT (template_key) DO NOTHING;
INSERT INTO cx_agent_templates(template_id,template_key,display_name,template_kind,content_json,content_digest,locked_fields_json,status,managed,created_by)
VALUES ('TPL_CODE_PROGRAM','CODE_PROGRAM','Code Programming Agent','BUSINESS','{"skills":["scm","task-plan"],"isolation":"DEDICATED_WORKSPACE","classification":"INTERNAL"}','v4.4.4-code-program','["skills","isolation"]','PUBLISHED','Y','SYSTEM') ON CONFLICT (template_key) DO NOTHING;
INSERT INTO cx_agent_templates(template_id,template_key,display_name,template_kind,content_json,content_digest,locked_fields_json,status,managed,created_by)
VALUES ('TPL_CODE_REVIEW','CODE_REVIEW','Code Review Agent','BUSINESS','{"skills":["scm","audit"],"read_only":true,"classification":"CONFIDENTIAL"}','v4.4.4-code-review','["skills","read_only"]','PUBLISHED','Y','SYSTEM') ON CONFLICT (template_key) DO NOTHING;
INSERT INTO cx_agent_templates(template_id,template_key,display_name,template_kind,content_json,content_digest,locked_fields_json,status,managed,created_by)
VALUES ('TPL_OFFICE_TEXT','OFFICE_TEXT','Office Text Agent','BUSINESS','{"skills":["office-text"],"classification":"INTERNAL"}','v4.4.4-office-text','["skills","classification"]','PUBLISHED','Y','SYSTEM') ON CONFLICT (template_key) DO NOTHING;
INSERT INTO cx_agent_templates(template_id,template_key,display_name,template_kind,content_json,content_digest,locked_fields_json,status,managed,created_by)
VALUES ('TPL_PPT_DESIGN','PPT_DESIGN','Presentation Design Agent','BUSINESS','{"skills":["office-text","ppt"],"classification":"INTERNAL"}','v4.4.4-ppt-design','["skills","classification"]','PUBLISHED','Y','SYSTEM') ON CONFLICT (template_key) DO NOTHING;
