-- Additive v4.4.13 policy. Only the schema-owner control plane may write it.
CREATE TABLE IF NOT EXISTS CX_PORTAL_KNOWLEDGE_POLICY (
 POLICY_ID VARCHAR(128) PRIMARY KEY,
 MODE VARCHAR(32) NOT NULL CHECK (MODE IN ('KNOWLEDGE_FIRST','KNOWLEDGE_ONLY')),
 ALLOW_MODEL_SUPPLEMENT CHAR(1) NOT NULL CHECK (ALLOW_MODEL_SUPPLEMENT IN ('Y','N')),
 DISCLOSURE_PROFILES_JSON TEXT NOT NULL,
 VERSION INTEGER NOT NULL CHECK (VERSION > 0),
 UPDATED_BY VARCHAR(128) NOT NULL,
 UPDATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
 REASON VARCHAR(2000) NOT NULL
);
INSERT INTO CX_PORTAL_KNOWLEDGE_POLICY
 (POLICY_ID,MODE,ALLOW_MODEL_SUPPLEMENT,DISCLOSURE_PROFILES_JSON,VERSION,UPDATED_BY,REASON)
 VALUES ('DEFAULT','KNOWLEDGE_FIRST','N','[]',1,'SYSTEM_BOOTSTRAP','Initial knowledge-first policy; model disclosure requires explicit configuration')
 ON CONFLICT (POLICY_ID) DO NOTHING;
REVOKE ALL ON CX_PORTAL_KNOWLEDGE_POLICY FROM PUBLIC;
