-- v4.4.14 database-authoritative model and external execution posture.
CREATE TABLE IF NOT EXISTS CX_MODEL_CAPABILITIES (
  CAPABILITY_KEY VARCHAR(128) PRIMARY KEY,
  STATE VARCHAR(32) NOT NULL CHECK (STATE IN ('OFF','READ_ONLY','PROPOSAL_ONLY','GOVERNED_EXECUTOR')),
  VERSION BIGINT NOT NULL DEFAULT 1 CHECK (VERSION > 0),
  MANDATORY CHAR(1) NOT NULL DEFAULT 'N' CHECK (MANDATORY IN ('Y','N')),
  SECURITY_DOMAIN_ID VARCHAR(128), SOURCE_DIGEST VARCHAR(64), SCHEMA_DIGEST VARCHAR(64),
  RESOURCE_SCOPE_JSON TEXT NOT NULL DEFAULT '{}', EVIDENCE_REF VARCHAR(256),
  REASON VARCHAR(2000) NOT NULL, UPDATED_BY VARCHAR(128) NOT NULL,
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS CX_MODEL_CAPABILITY_HISTORY (
  HISTORY_ID VARCHAR(128) PRIMARY KEY, CAPABILITY_KEY VARCHAR(128) NOT NULL,
  FROM_STATE VARCHAR(32) NOT NULL, TO_STATE VARCHAR(32) NOT NULL,
  EXPECTED_VERSION BIGINT NOT NULL, EVIDENCE_REF VARCHAR(256), REASON VARCHAR(2000) NOT NULL,
  CHANGED_BY VARCHAR(128) NOT NULL, CHANGED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS CX_MODEL_EXECUTION_EVIDENCE (
  EVIDENCE_ID VARCHAR(128) PRIMARY KEY, REQUEST_ID VARCHAR(128) NOT NULL,
  PROVIDER_KEY VARCHAR(128), MODEL_ID VARCHAR(256), FINISH_STATE VARCHAR(32) NOT NULL,
  TOOL_CALL_COUNT INTEGER NOT NULL DEFAULT 0, STRUCTURED_OUTPUT_STATE VARCHAR(32) NOT NULL,
  USAGE_JSON TEXT NOT NULL DEFAULT '{}', LATENCY_MS BIGINT NOT NULL DEFAULT 0,
  TIMEOUT_STATE VARCHAR(32) NOT NULL DEFAULT 'NONE', CANCELLATION_STATE VARCHAR(32) NOT NULL DEFAULT 'NONE',
  RETRY_COUNT INTEGER NOT NULL DEFAULT 0, IDEMPOTENCY_KEY VARCHAR(256), EVIDENCE_DIGEST VARCHAR(64) NOT NULL,
  CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CX_MODEL_CAPABILITIES(CAPABILITY_KEY,STATE,MANDATORY,REASON,UPDATED_BY)
VALUES
 ('model_reasoning','READ_ONLY','Y','Reasoning metadata is visible only as bounded metadata','SYSTEM_BOOTSTRAP'),
 ('structured_output','READ_ONLY','Y','Structured output requires registered schema validation','SYSTEM_BOOTSTRAP'),
 ('model_tool_calls','PROPOSAL_ONLY','Y','Model tool calls create proposals by default','SYSTEM_BOOTSTRAP'),
 ('mcp_discovery','OFF','N','External MCP discovery requires explicit trust configuration','SYSTEM_BOOTSTRAP'),
 ('mcp_execution','OFF','N','External MCP execution is disabled by default','SYSTEM_BOOTSTRAP'),
 ('a2a_exchange','OFF','N','External A2A exchange is disabled by default','SYSTEM_BOOTSTRAP'),
 ('governed_execution','PROPOSAL_ONLY','Y','High-impact execution requires Human approval','SYSTEM_BOOTSTRAP')
ON CONFLICT (CAPABILITY_KEY) DO NOTHING;
REVOKE ALL ON CX_MODEL_CAPABILITIES, CX_MODEL_CAPABILITY_HISTORY, CX_MODEL_EXECUTION_EVIDENCE FROM PUBLIC;
