CREATE TABLE IF NOT EXISTS CX_TASK_MIGRATION_CONTROL (
  MIGRATION_KEY VARCHAR(64) PRIMARY KEY,
  STATE VARCHAR(20) NOT NULL CHECK (STATE IN ('PREPARING','DUAL_WRITE','CUTOVER','VERIFIED','ROLLBACK')),
  VERSION BIGINT NOT NULL DEFAULT 1,
  UPDATED_BY VARCHAR(128) NOT NULL,
  REASON VARCHAR(2000) NOT NULL,
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO CX_TASK_MIGRATION_CONTROL(MIGRATION_KEY,STATE,UPDATED_BY,REASON)
VALUES ('TASK_STEPS','PREPARING','SYSTEM_BOOTSTRAP','v4.4.15 online task migration')
ON CONFLICT (MIGRATION_KEY) DO NOTHING;
