"""Portable relational contracts for additive Agent extension migrations.

Adapter generators own concrete types, grants and immutable-column triggers.
These statements are never executed at application startup.
"""

TABLES = {
    "CX_PROVIDER_CAP_PROBES": {
        "columns": ["PROBE_ID", "PROFILE_ID", "PROFILE_VERSION", "MODEL_ID", "API_DIALECT", "CAPABILITY_KEY", "STATUS", "PARAMETER_DIGEST", "SCHEMA_DIGEST", "EVIDENCE_DIGEST", "OBSERVATION_JSON", "STARTED_AT", "COMPLETED_AT", "EXPIRES_AT", "ACTOR_ID"],
        "immutable_columns": ["PROBE_ID", "PROFILE_ID", "PROFILE_VERSION", "MODEL_ID", "API_DIALECT", "CAPABILITY_KEY", "PARAMETER_DIGEST", "SCHEMA_DIGEST", "STARTED_AT", "ACTOR_ID"],
        "definition": "PROBE_ID VARCHAR(128) PRIMARY KEY, PROFILE_ID VARCHAR(128) NOT NULL REFERENCES CX_LLM_PROVIDER_PROFILES(PROFILE_ID), PROFILE_VERSION INTEGER NOT NULL CHECK(PROFILE_VERSION>0), MODEL_ID VARCHAR(256) NOT NULL, API_DIALECT VARCHAR(64) NOT NULL, CAPABILITY_KEY VARCHAR(64) NOT NULL, STATUS VARCHAR(32) NOT NULL, PARAMETER_DIGEST VARCHAR(64) NOT NULL, SCHEMA_DIGEST VARCHAR(64) NOT NULL, EVIDENCE_DIGEST VARCHAR(64), OBSERVATION_JSON TEXT, STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP, EXPIRES_AT TIMESTAMP NOT NULL, ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID)",
    },
    "CX_PROVIDER_PARAM_CONTRACTS": {
        "columns": ["PROFILE_ID", "PROFILE_VERSION", "PARAMETER_KEY", "VALUE_JSON", "PROBE_ID", "CONTRACT_DIGEST", "STATUS", "APPROVED_BY", "CREATED_AT"],
        "immutable_columns": ["PROFILE_ID", "PROFILE_VERSION", "PARAMETER_KEY", "VALUE_JSON", "PROBE_ID", "CONTRACT_DIGEST", "APPROVED_BY", "CREATED_AT"],
        "definition": "PROFILE_ID VARCHAR(128) NOT NULL REFERENCES CX_LLM_PROVIDER_PROFILES(PROFILE_ID), PROFILE_VERSION INTEGER NOT NULL CHECK(PROFILE_VERSION>0), PARAMETER_KEY VARCHAR(64) NOT NULL, VALUE_JSON TEXT NOT NULL, PROBE_ID VARCHAR(128) NOT NULL REFERENCES CX_PROVIDER_CAP_PROBES(PROBE_ID), CONTRACT_DIGEST VARCHAR(64) NOT NULL, STATUS VARCHAR(24) NOT NULL CHECK(STATUS IN ('ACTIVE','REVOKED')), APPROVED_BY VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(PROFILE_ID,PROFILE_VERSION,PARAMETER_KEY)",
    },
    "CX_PROTOCOL_ENDPOINTS": {
        "columns": ["ENDPOINT_ID", "ENDPOINT_NAME", "PROTOCOL_KIND", "OWNER_ID", "SECURITY_DOMAIN_ID", "CURRENT_REVISION", "STATUS", "AUTH_CIPHER", "VERSION", "UPDATED_BY", "REASON", "CREATED_AT", "UPDATED_AT"],
        "immutable_columns": ["ENDPOINT_ID", "PROTOCOL_KIND", "OWNER_ID", "SECURITY_DOMAIN_ID", "CREATED_AT"],
        "definition": "ENDPOINT_ID VARCHAR(128) PRIMARY KEY, ENDPOINT_NAME VARCHAR(256) NOT NULL, PROTOCOL_KIND VARCHAR(24) NOT NULL CHECK(PROTOCOL_KIND IN ('MCP','A2A','OTLP')), OWNER_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), SECURITY_DOMAIN_ID VARCHAR(128) NOT NULL REFERENCES CX_SECURITY_DOMAINS(SECURITY_DOMAIN_ID), CURRENT_REVISION INTEGER NOT NULL CHECK(CURRENT_REVISION>0), STATUS VARCHAR(24) NOT NULL CHECK(STATUS IN ('ACTIVE','REVOKED')), AUTH_CIPHER TEXT, VERSION INTEGER DEFAULT 1 NOT NULL CHECK(VERSION>0), UPDATED_BY VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), REASON VARCHAR(2000) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
    "CX_PROTOCOL_REVISIONS": {
        "columns": ["ENDPOINT_ID", "REVISION_NO", "ENDPOINT_URL", "TRANSPORT_KIND", "PROTOCOL_VERSION", "SDK_VERSION", "ISSUER_URL", "RESOURCE_URL", "CONTRACT_DIGEST", "TIMEOUT_SECONDS", "MAX_RESPONSE_BYTES", "REGISTERED_BY", "CREATED_AT"],
        "immutable_columns": ["ENDPOINT_ID", "REVISION_NO", "ENDPOINT_URL", "TRANSPORT_KIND", "PROTOCOL_VERSION", "SDK_VERSION", "ISSUER_URL", "RESOURCE_URL", "CONTRACT_DIGEST", "TIMEOUT_SECONDS", "MAX_RESPONSE_BYTES", "REGISTERED_BY", "CREATED_AT"],
        "definition": "ENDPOINT_ID VARCHAR(128) NOT NULL REFERENCES CX_PROTOCOL_ENDPOINTS(ENDPOINT_ID), REVISION_NO INTEGER NOT NULL CHECK(REVISION_NO>0), ENDPOINT_URL VARCHAR(1000) NOT NULL, TRANSPORT_KIND VARCHAR(32) NOT NULL, PROTOCOL_VERSION VARCHAR(64) NOT NULL, SDK_VERSION VARCHAR(64) NOT NULL, ISSUER_URL VARCHAR(1000), RESOURCE_URL VARCHAR(1000), CONTRACT_DIGEST VARCHAR(64) NOT NULL, TIMEOUT_SECONDS INTEGER NOT NULL CHECK(TIMEOUT_SECONDS BETWEEN 1 AND 60), MAX_RESPONSE_BYTES INTEGER NOT NULL CHECK(MAX_RESPONSE_BYTES BETWEEN 1024 AND 4194304), REGISTERED_BY VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(ENDPOINT_ID,REVISION_NO)",
    },
    "CX_PROTOCOL_TOOLS": {
        "columns": ["ENDPOINT_ID", "REVISION_NO", "TOOL_NAME", "TOOL_DIGEST", "DISPLAY_NAME", "DESCRIPTION", "INPUT_SCHEMA_JSON", "OUTPUT_SCHEMA_JSON", "READ_ONLY", "STATUS", "APPROVED_BY", "DISCOVERED_AT"],
        "immutable_columns": ["ENDPOINT_ID", "REVISION_NO", "TOOL_NAME", "TOOL_DIGEST", "DISPLAY_NAME", "DESCRIPTION", "INPUT_SCHEMA_JSON", "OUTPUT_SCHEMA_JSON", "READ_ONLY", "DISCOVERED_AT"],
        "definition": "ENDPOINT_ID VARCHAR(128) NOT NULL, REVISION_NO INTEGER NOT NULL, TOOL_NAME VARCHAR(256) NOT NULL, TOOL_DIGEST VARCHAR(64) NOT NULL, DISPLAY_NAME VARCHAR(256) NOT NULL, DESCRIPTION VARCHAR(2000), INPUT_SCHEMA_JSON TEXT NOT NULL, OUTPUT_SCHEMA_JSON TEXT, READ_ONLY INTEGER NOT NULL CHECK(READ_ONLY IN (0,1)), STATUS VARCHAR(24) NOT NULL CHECK(STATUS IN ('DISCOVERED','APPROVED','REVOKED')), APPROVED_BY VARCHAR(128) REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), DISCOVERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(ENDPOINT_ID,REVISION_NO,TOOL_NAME,TOOL_DIGEST), FOREIGN KEY(ENDPOINT_ID,REVISION_NO) REFERENCES CX_PROTOCOL_REVISIONS(ENDPOINT_ID,REVISION_NO)",
    },
    "CX_PROTOCOL_CALLS": {
        "columns": ["CALL_ID", "ENDPOINT_ID", "REVISION_NO", "TOOL_NAME", "TOOL_DIGEST", "ACTOR_ID", "SECURITY_DOMAIN_ID", "PERMISSION_VERSION", "ENDPOINT_VERSION", "IDEMPOTENCY_KEY", "PAYLOAD_DIGEST", "STATUS", "RESULT_CIPHER", "RESULT_DIGEST", "CANCEL_REQUESTED", "CREATED_AT", "COMPLETED_AT"],
        "immutable_columns": ["CALL_ID", "ENDPOINT_ID", "REVISION_NO", "TOOL_NAME", "TOOL_DIGEST", "ACTOR_ID", "SECURITY_DOMAIN_ID", "PERMISSION_VERSION", "ENDPOINT_VERSION", "IDEMPOTENCY_KEY", "PAYLOAD_DIGEST", "CREATED_AT"],
        "definition": "CALL_ID VARCHAR(128) PRIMARY KEY, ENDPOINT_ID VARCHAR(128) NOT NULL, REVISION_NO INTEGER NOT NULL, TOOL_NAME VARCHAR(256) NOT NULL, TOOL_DIGEST VARCHAR(64) NOT NULL, ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), SECURITY_DOMAIN_ID VARCHAR(128) NOT NULL REFERENCES CX_SECURITY_DOMAINS(SECURITY_DOMAIN_ID), PERMISSION_VERSION INTEGER NOT NULL, ENDPOINT_VERSION INTEGER NOT NULL, IDEMPOTENCY_KEY VARCHAR(128) NOT NULL, PAYLOAD_DIGEST VARCHAR(64) NOT NULL, STATUS VARCHAR(32) NOT NULL, RESULT_CIPHER TEXT, RESULT_DIGEST VARCHAR(64), CANCEL_REQUESTED INTEGER DEFAULT 0 NOT NULL CHECK(CANCEL_REQUESTED IN (0,1)), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP, UNIQUE(ACTOR_ID,IDEMPOTENCY_KEY), FOREIGN KEY(ENDPOINT_ID,REVISION_NO,TOOL_NAME,TOOL_DIGEST) REFERENCES CX_PROTOCOL_TOOLS(ENDPOINT_ID,REVISION_NO,TOOL_NAME,TOOL_DIGEST)",
    },
    "CX_PROTOCOL_ATTEMPTS": {
        "columns": ["ATTEMPT_ID", "CALL_ID", "ATTEMPT_NO", "FENCING_TOKEN", "STATUS", "LEASE_EXPIRES_AT", "HTTP_STATUS", "ERROR_CODE", "STARTED_AT", "COMPLETED_AT"],
        "immutable_columns": ["ATTEMPT_ID", "CALL_ID", "ATTEMPT_NO", "FENCING_TOKEN", "LEASE_EXPIRES_AT", "STARTED_AT"],
        "definition": "ATTEMPT_ID VARCHAR(128) PRIMARY KEY, CALL_ID VARCHAR(128) NOT NULL REFERENCES CX_PROTOCOL_CALLS(CALL_ID), ATTEMPT_NO INTEGER NOT NULL CHECK(ATTEMPT_NO>0), FENCING_TOKEN INTEGER NOT NULL CHECK(FENCING_TOKEN>0), STATUS VARCHAR(32) NOT NULL, LEASE_EXPIRES_AT TIMESTAMP NOT NULL, HTTP_STATUS INTEGER, ERROR_CODE VARCHAR(128), STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP, UNIQUE(CALL_ID,ATTEMPT_NO)",
    },
    "CX_PROTOCOL_CREDENTIALS": {
        "columns": ["CALL_ID", "INSTANCE_ID", "TOKEN_DIGEST", "FENCING_TOKEN", "CREATED_AT"],
        "immutable_columns": ["CALL_ID", "INSTANCE_ID", "TOKEN_DIGEST", "FENCING_TOKEN", "CREATED_AT"],
        "definition": "CALL_ID VARCHAR(128) PRIMARY KEY REFERENCES CX_PROTOCOL_CALLS(CALL_ID), INSTANCE_ID VARCHAR(128) NOT NULL REFERENCES CX_AGENT_INSTANCES(INSTANCE_ID), TOKEN_DIGEST VARCHAR(64) NOT NULL REFERENCES CX_AGENT_ACCESS_TOKENS(TOKEN_DIGEST), FENCING_TOKEN INTEGER NOT NULL CHECK(FENCING_TOKEN>0), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
    "CX_CONTEXT_DERIVATIONS": {
        "columns": ["DERIVATION_ID", "ASSEMBLY_ID", "ACTOR_ID", "SECURITY_DOMAIN_ID", "SOURCE_DIGEST", "CONTENT_DIGEST", "TOKEN_BUDGET", "METHOD_KEY", "CONTENT_CIPHER", "CREATED_AT"],
        "immutable_columns": ["DERIVATION_ID", "ASSEMBLY_ID", "ACTOR_ID", "SECURITY_DOMAIN_ID", "SOURCE_DIGEST", "CONTENT_DIGEST", "TOKEN_BUDGET", "METHOD_KEY", "CONTENT_CIPHER", "CREATED_AT"],
        "definition": "DERIVATION_ID VARCHAR(128) PRIMARY KEY, ASSEMBLY_ID VARCHAR(128) NOT NULL REFERENCES CX_CONTEXT_ASSEMBLIES(ASSEMBLY_ID), ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), SECURITY_DOMAIN_ID VARCHAR(128) NOT NULL REFERENCES CX_SECURITY_DOMAINS(SECURITY_DOMAIN_ID), SOURCE_DIGEST VARCHAR(64) NOT NULL, CONTENT_DIGEST VARCHAR(64) NOT NULL, TOKEN_BUDGET INTEGER NOT NULL CHECK(TOKEN_BUDGET>0), METHOD_KEY VARCHAR(64) NOT NULL, CONTENT_CIPHER TEXT NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
    "CX_CONTEXT_DERIVED_SOURCES": {
        "columns": ["DERIVATION_ID", "ASSEMBLY_ID", "ITEM_NO"],
        "immutable_columns": ["DERIVATION_ID", "ASSEMBLY_ID", "ITEM_NO"],
        "definition": "DERIVATION_ID VARCHAR(128) NOT NULL REFERENCES CX_CONTEXT_DERIVATIONS(DERIVATION_ID), ASSEMBLY_ID VARCHAR(128) NOT NULL, ITEM_NO INTEGER NOT NULL, PRIMARY KEY(DERIVATION_ID,ASSEMBLY_ID,ITEM_NO), FOREIGN KEY(ASSEMBLY_ID,ITEM_NO) REFERENCES CX_CONTEXT_ASSEMBLY_ITEMS(ASSEMBLY_ID,ITEM_NO)",
    },
    "CX_ANSWER_EVAL_CASES": {
        "columns": ["CASE_ID", "VERSION", "CASE_NAME", "QUERY_TEXT", "EXPECTED_MODE", "EXPECTED_ENTITIES_JSON", "STATUS", "APPROVED_BY", "CASE_DIGEST", "CREATED_AT"],
        "immutable_columns": ["CASE_ID", "VERSION", "CASE_NAME", "QUERY_TEXT", "EXPECTED_MODE", "EXPECTED_ENTITIES_JSON", "APPROVED_BY", "CASE_DIGEST", "CREATED_AT"],
        "definition": "CASE_ID VARCHAR(128) NOT NULL, VERSION INTEGER NOT NULL CHECK(VERSION>0), CASE_NAME VARCHAR(256) NOT NULL, QUERY_TEXT VARCHAR(2000) NOT NULL, EXPECTED_MODE VARCHAR(32) NOT NULL, EXPECTED_ENTITIES_JSON TEXT NOT NULL, STATUS VARCHAR(24) NOT NULL CHECK(STATUS IN ('ACTIVE','RETIRED')), APPROVED_BY VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), CASE_DIGEST VARCHAR(64) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(CASE_ID,VERSION)",
    },
    "CX_ANSWER_EVAL_RESULTS": {
        "columns": ["RESULT_ID", "CASE_ID", "CASE_VERSION", "PROFILE_ID", "PROFILE_VERSION", "ENTRY_KIND", "ACTOR_ID", "OBSERVED_MODE", "PASSED", "LATENCY_MS", "POLICY_DIGEST", "RESULT_DIGEST", "DETAIL_JSON", "CREATED_AT"],
        "immutable_columns": ["RESULT_ID", "CASE_ID", "CASE_VERSION", "PROFILE_ID", "PROFILE_VERSION", "ENTRY_KIND", "ACTOR_ID", "OBSERVED_MODE", "PASSED", "LATENCY_MS", "POLICY_DIGEST", "RESULT_DIGEST", "DETAIL_JSON", "CREATED_AT"],
        "definition": "RESULT_ID VARCHAR(128) PRIMARY KEY, CASE_ID VARCHAR(128) NOT NULL, CASE_VERSION INTEGER NOT NULL, PROFILE_ID VARCHAR(128) NOT NULL REFERENCES CX_LLM_PROVIDER_PROFILES(PROFILE_ID), PROFILE_VERSION INTEGER NOT NULL, ENTRY_KIND VARCHAR(24) NOT NULL CHECK(ENTRY_KIND IN ('PORTAL','CHANNEL')), ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), OBSERVED_MODE VARCHAR(32) NOT NULL, PASSED INTEGER NOT NULL CHECK(PASSED IN (0,1)), LATENCY_MS INTEGER NOT NULL CHECK(LATENCY_MS>=0), POLICY_DIGEST VARCHAR(64) NOT NULL, RESULT_DIGEST VARCHAR(64) NOT NULL, DETAIL_JSON TEXT NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY(CASE_ID,CASE_VERSION) REFERENCES CX_ANSWER_EVAL_CASES(CASE_ID,VERSION)",
    },
    "CX_MANAGED_INPUT_ASSETS": {
        "columns": ["ASSET_ID", "OWNER_ID", "SECURITY_DOMAIN_ID", "FILE_NAME", "MEDIA_TYPE", "BYTE_COUNT", "CONTENT_DIGEST", "CONTENT_CIPHER", "EXTRACTED_CIPHER", "STATUS", "VERSION", "CREATED_AT"],
        "immutable_columns": ["ASSET_ID", "OWNER_ID", "SECURITY_DOMAIN_ID", "FILE_NAME", "MEDIA_TYPE", "BYTE_COUNT", "CONTENT_DIGEST", "CONTENT_CIPHER", "EXTRACTED_CIPHER", "CREATED_AT"],
        "definition": "ASSET_ID VARCHAR(128) PRIMARY KEY, OWNER_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), SECURITY_DOMAIN_ID VARCHAR(128) NOT NULL REFERENCES CX_SECURITY_DOMAINS(SECURITY_DOMAIN_ID), FILE_NAME VARCHAR(256) NOT NULL, MEDIA_TYPE VARCHAR(128) NOT NULL, BYTE_COUNT INTEGER NOT NULL CHECK(BYTE_COUNT BETWEEN 1 AND 4194304), CONTENT_DIGEST VARCHAR(64) NOT NULL, CONTENT_CIPHER TEXT NOT NULL, EXTRACTED_CIPHER TEXT, STATUS VARCHAR(24) NOT NULL CHECK(STATUS IN ('ACTIVE','REVOKED')), VERSION INTEGER DEFAULT 1 NOT NULL CHECK(VERSION>0), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
    "CX_MANAGED_ASSET_USES": {
        "columns": ["USE_ID", "ASSET_ID", "ASSET_VERSION", "ACTOR_ID", "PROFILE_ID", "PROFILE_VERSION", "STATUS", "INPUT_DIGEST", "OUTPUT_DIGEST", "CREATED_AT", "COMPLETED_AT"],
        "immutable_columns": ["USE_ID", "ASSET_ID", "ASSET_VERSION", "ACTOR_ID", "PROFILE_ID", "PROFILE_VERSION", "INPUT_DIGEST", "CREATED_AT"],
        "definition": "USE_ID VARCHAR(128) PRIMARY KEY, ASSET_ID VARCHAR(128) NOT NULL REFERENCES CX_MANAGED_INPUT_ASSETS(ASSET_ID), ASSET_VERSION INTEGER NOT NULL, ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), PROFILE_ID VARCHAR(128) NOT NULL REFERENCES CX_LLM_PROVIDER_PROFILES(PROFILE_ID), PROFILE_VERSION INTEGER NOT NULL, STATUS VARCHAR(32) NOT NULL, INPUT_DIGEST VARCHAR(64) NOT NULL, OUTPUT_DIGEST VARCHAR(64), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP",
    },
    "CX_TELEMETRY_ATTEMPTS": {
        "columns": ["ATTEMPT_ID", "DELIVERY_ID", "ENDPOINT_ID", "REVISION_NO", "ATTEMPT_NO", "STATUS", "PROJECTION_DIGEST", "HTTP_STATUS", "ERROR_CODE", "LEASE_EXPIRES_AT", "STARTED_AT", "COMPLETED_AT"],
        "immutable_columns": ["ATTEMPT_ID", "DELIVERY_ID", "ENDPOINT_ID", "REVISION_NO", "ATTEMPT_NO", "PROJECTION_DIGEST", "LEASE_EXPIRES_AT", "STARTED_AT"],
        "definition": "ATTEMPT_ID VARCHAR(128) PRIMARY KEY, DELIVERY_ID VARCHAR(128) NOT NULL REFERENCES GRAPH_TELEMETRY_DELIVERIES(DELIVERY_ID), ENDPOINT_ID VARCHAR(128) NOT NULL, REVISION_NO INTEGER NOT NULL, ATTEMPT_NO INTEGER NOT NULL CHECK(ATTEMPT_NO>0), STATUS VARCHAR(32) NOT NULL, PROJECTION_DIGEST VARCHAR(64) NOT NULL, HTTP_STATUS INTEGER, ERROR_CODE VARCHAR(128), LEASE_EXPIRES_AT TIMESTAMP NOT NULL, STARTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, COMPLETED_AT TIMESTAMP, UNIQUE(DELIVERY_ID,ATTEMPT_NO), FOREIGN KEY(ENDPOINT_ID,REVISION_NO) REFERENCES CX_PROTOCOL_REVISIONS(ENDPOINT_ID,REVISION_NO)",
    },
    "CX_TELEMETRY_PAYLOADS": {
        "columns": ["DELIVERY_ID", "ENDPOINT_ID", "REVISION_NO", "ACTOR_ID", "PROJECTION_JSON", "PROJECTION_DIGEST", "CREATED_AT"],
        "immutable_columns": ["DELIVERY_ID", "ENDPOINT_ID", "REVISION_NO", "ACTOR_ID", "PROJECTION_JSON", "PROJECTION_DIGEST", "CREATED_AT"],
        "definition": "DELIVERY_ID VARCHAR(128) PRIMARY KEY REFERENCES GRAPH_TELEMETRY_DELIVERIES(DELIVERY_ID), ENDPOINT_ID VARCHAR(128) NOT NULL, REVISION_NO INTEGER NOT NULL, ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), PROJECTION_JSON TEXT NOT NULL, PROJECTION_DIGEST VARCHAR(64) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY(ENDPOINT_ID,REVISION_NO) REFERENCES CX_PROTOCOL_REVISIONS(ENDPOINT_ID,REVISION_NO)",
    },
    "CX_GRAPH_FORKS": {
        "columns": ["CHILD_RUN_ID", "PARENT_RUN_ID", "CHECKPOINT_ID", "SOURCE_PLAN_DIGEST", "SNAPSHOT_HASH", "ACTOR_ID", "REQUEST_DIGEST", "REASON", "CREATED_AT"],
        "immutable_columns": ["CHILD_RUN_ID", "PARENT_RUN_ID", "CHECKPOINT_ID", "SOURCE_PLAN_DIGEST", "SNAPSHOT_HASH", "ACTOR_ID", "REQUEST_DIGEST", "REASON", "CREATED_AT"],
        "definition": "CHILD_RUN_ID VARCHAR(128) PRIMARY KEY REFERENCES GRAPH_RUNS(RUN_ID), PARENT_RUN_ID VARCHAR(128) NOT NULL REFERENCES GRAPH_RUNS(RUN_ID), CHECKPOINT_ID VARCHAR(128) NOT NULL REFERENCES GRAPH_CHECKPOINTS(CHECKPOINT_ID), SOURCE_PLAN_DIGEST VARCHAR(128) NOT NULL, SNAPSHOT_HASH VARCHAR(128) NOT NULL, ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), REQUEST_DIGEST VARCHAR(64) NOT NULL, REASON VARCHAR(2000) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
    "CX_AGENT_DIAGNOSTICS": {
        "columns": ["DIAGNOSTIC_ID", "ACTOR_ID", "SECURITY_DOMAIN_ID", "CHECK_KIND", "RESOURCE_ID", "STATUS", "RESULT_JSON", "RESULT_DIGEST", "CREATED_AT"],
        "immutable_columns": ["DIAGNOSTIC_ID", "ACTOR_ID", "SECURITY_DOMAIN_ID", "CHECK_KIND", "RESOURCE_ID", "STATUS", "RESULT_JSON", "RESULT_DIGEST", "CREATED_AT"],
        "definition": "DIAGNOSTIC_ID VARCHAR(128) PRIMARY KEY, ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), SECURITY_DOMAIN_ID VARCHAR(128) NOT NULL REFERENCES CX_SECURITY_DOMAINS(SECURITY_DOMAIN_ID), CHECK_KIND VARCHAR(64) NOT NULL, RESOURCE_ID VARCHAR(128), STATUS VARCHAR(24) NOT NULL, RESULT_JSON TEXT NOT NULL, RESULT_DIGEST VARCHAR(64) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
    "CX_A2A_REQUESTS": {
        "columns": ["PROTOCOL_TASK_ID", "SECURITY_DOMAIN_ID", "ACTOR_ID", "CONTEXT_ID", "MESSAGE_ID", "REQUEST_DIGEST", "CREATED_AT"],
        "immutable_columns": ["PROTOCOL_TASK_ID", "SECURITY_DOMAIN_ID", "ACTOR_ID", "CONTEXT_ID", "MESSAGE_ID", "REQUEST_DIGEST", "CREATED_AT"],
        "definition": "PROTOCOL_TASK_ID VARCHAR(256) PRIMARY KEY REFERENCES GRAPH_PROTOCOL_TASKS(PROTOCOL_TASK_ID), SECURITY_DOMAIN_ID VARCHAR(128) NOT NULL REFERENCES CX_SECURITY_DOMAINS(SECURITY_DOMAIN_ID), ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), CONTEXT_ID VARCHAR(128) NOT NULL, MESSAGE_ID VARCHAR(128) NOT NULL, REQUEST_DIGEST VARCHAR(64) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE(ACTOR_ID,MESSAGE_ID)",
    },
    "CX_A2A_CREDENTIALS": {
        "columns": ["PROTOCOL_TASK_ID", "INSTANCE_ID", "TOKEN_DIGEST", "FENCING_TOKEN", "CREATED_AT"],
        "immutable_columns": ["PROTOCOL_TASK_ID", "INSTANCE_ID", "TOKEN_DIGEST", "FENCING_TOKEN", "CREATED_AT"],
        "definition": "PROTOCOL_TASK_ID VARCHAR(256) PRIMARY KEY REFERENCES CX_A2A_REQUESTS(PROTOCOL_TASK_ID), INSTANCE_ID VARCHAR(128) NOT NULL REFERENCES CX_AGENT_INSTANCES(INSTANCE_ID), TOKEN_DIGEST VARCHAR(64) NOT NULL REFERENCES CX_AGENT_ACCESS_TOKENS(TOKEN_DIGEST), FENCING_TOKEN INTEGER NOT NULL CHECK(FENCING_TOKEN>0), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
    "CX_FRAMEWORK_EXECUTIONS": {
        "columns": ["EXECUTION_ID", "ACTOR_ID", "SECURITY_DOMAIN_ID", "FRAMEWORK_KEY", "FRAMEWORK_VERSION", "ADAPTER_DIGEST", "ROOTFS_DIGEST", "INPUT_DIGEST", "OBSERVATION_JSON", "OBSERVATION_DIGEST", "CREATED_AT"],
        "immutable_columns": ["EXECUTION_ID", "ACTOR_ID", "SECURITY_DOMAIN_ID", "FRAMEWORK_KEY", "FRAMEWORK_VERSION", "ADAPTER_DIGEST", "ROOTFS_DIGEST", "INPUT_DIGEST", "CREATED_AT"],
        "definition": "EXECUTION_ID VARCHAR(128) PRIMARY KEY REFERENCES CX_RUNTIME_EXECUTIONS(EXECUTION_ID), ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), SECURITY_DOMAIN_ID VARCHAR(128) NOT NULL REFERENCES CX_SECURITY_DOMAINS(SECURITY_DOMAIN_ID), FRAMEWORK_KEY VARCHAR(64) NOT NULL, FRAMEWORK_VERSION VARCHAR(64) NOT NULL, ADAPTER_DIGEST VARCHAR(64) NOT NULL, ROOTFS_DIGEST VARCHAR(64) NOT NULL, INPUT_DIGEST VARCHAR(64) NOT NULL, OBSERVATION_JSON TEXT, OBSERVATION_DIGEST VARCHAR(64), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
    "CX_EXECUTION_OBSERVATIONS": {
        "columns": ["EXECUTION_ID", "FENCING_TOKEN", "QUEUE_MS", "PROVIDER_LATENCY_MS", "FIRST_TOKEN_MS", "CANCELLATION_STATE", "FINISH_CODE", "CREATED_AT"],
        "immutable_columns": ["EXECUTION_ID", "FENCING_TOKEN", "QUEUE_MS", "PROVIDER_LATENCY_MS", "FIRST_TOKEN_MS", "CANCELLATION_STATE", "FINISH_CODE", "CREATED_AT"],
        "definition": "EXECUTION_ID VARCHAR(128) PRIMARY KEY REFERENCES CX_RUNTIME_EXECUTIONS(EXECUTION_ID), FENCING_TOKEN INTEGER NOT NULL CHECK(FENCING_TOKEN>0), QUEUE_MS INTEGER CHECK(QUEUE_MS>=0), PROVIDER_LATENCY_MS INTEGER CHECK(PROVIDER_LATENCY_MS>=0), FIRST_TOKEN_MS INTEGER CHECK(FIRST_TOKEN_MS>=0), CANCELLATION_STATE VARCHAR(32) NOT NULL CHECK(CANCELLATION_STATE IN ('NOT_REQUESTED','LOCAL_CANCELLED','PROVIDER_UNCONFIRMED')), FINISH_CODE VARCHAR(128) NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
}


STATUS_RULES = {
    "CX_PROVIDER_CAP_PROBES": ("RUNNING", "VERIFIED", "UNSUPPORTED", "FAILED", "STALE", "CLIENT_CANCELLED"),
    "CX_PROTOCOL_CALLS": ("PENDING", "SENDING", "SUCCEEDED", "FAILED", "CANCEL_REQUESTED", "CANCELLED", "UNOBSERVED"),
    "CX_PROTOCOL_ATTEMPTS": ("SENDING", "SUCCEEDED", "FAILED", "CANCELLED", "UNOBSERVED"),
    "CX_MANAGED_ASSET_USES": ("SENDING", "SUCCEEDED", "FAILED", "UNOBSERVED"),
    "CX_TELEMETRY_ATTEMPTS": ("SENDING", "DELIVERED", "FAILED", "UNOBSERVED"),
    "CX_AGENT_DIAGNOSTICS": ("HEALTHY", "FINDINGS", "UNAVAILABLE"),
}


def schema_statements():
    statements = []
    for name, table in TABLES.items():
        definition = table["definition"]
        if name in STATUS_RULES:
            values = ",".join("'" + state + "'" for state in STATUS_RULES[name])
            for width in (24, 32):
                source = f"STATUS VARCHAR({width}) NOT NULL,"
                definition = definition.replace(source, f"STATUS VARCHAR({width}) NOT NULL CHECK(STATUS IN ({values})),")
        statements.append(f"CREATE TABLE {name} ({definition})")
    return statements
