"""Additive version, execution and source bindings after extension migration 98."""
TABLES = {
    "CX_A2A_TASK_BINDINGS": {
        "columns": ["PROTOCOL_TASK_ID", "ENDPOINT_ID", "REVISION_NO", "CREATED_AT"],
        "immutable_columns": ["PROTOCOL_TASK_ID", "ENDPOINT_ID", "REVISION_NO", "CREATED_AT"],
        "definition": "PROTOCOL_TASK_ID VARCHAR(256) PRIMARY KEY REFERENCES CX_A2A_REQUESTS(PROTOCOL_TASK_ID), ENDPOINT_ID VARCHAR(128) NOT NULL, REVISION_NO INTEGER NOT NULL CHECK(REVISION_NO>0), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, FOREIGN KEY(ENDPOINT_ID,REVISION_NO) REFERENCES CX_PROTOCOL_REVISIONS(ENDPOINT_ID,REVISION_NO)",
    },
    "CX_A2A_GRAPH_BINDINGS": {
        "columns": ["ENDPOINT_ID", "REVISION_NO", "GRAPH_VERSION_ID", "PLAN_ID", "PLAN_DIGEST", "APPROVED_BY", "CREATED_AT"],
        "immutable_columns": ["ENDPOINT_ID", "REVISION_NO", "GRAPH_VERSION_ID", "PLAN_ID", "PLAN_DIGEST", "APPROVED_BY", "CREATED_AT"],
        "definition": "ENDPOINT_ID VARCHAR(128) NOT NULL, REVISION_NO INTEGER NOT NULL CHECK(REVISION_NO>0), GRAPH_VERSION_ID VARCHAR(128) NOT NULL REFERENCES GRAPH_VERSIONS(GRAPH_VERSION_ID), PLAN_ID VARCHAR(128) NOT NULL REFERENCES GRAPH_COMPILE_PLANS(PLAN_ID), PLAN_DIGEST VARCHAR(64) NOT NULL, APPROVED_BY VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(ENDPOINT_ID,REVISION_NO), FOREIGN KEY(ENDPOINT_ID,REVISION_NO) REFERENCES CX_PROTOCOL_REVISIONS(ENDPOINT_ID,REVISION_NO)",
    },
    "CX_FRAMEWORK_BINDINGS": {
        "columns": ["EXECUTION_ID", "PROFILE_ID", "PROFILE_VERSION", "PERMISSION_VERSION", "TARGET_ID", "CREATED_AT"],
        "immutable_columns": ["EXECUTION_ID", "PROFILE_ID", "PROFILE_VERSION", "PERMISSION_VERSION", "TARGET_ID", "CREATED_AT"],
        "definition": "EXECUTION_ID VARCHAR(128) PRIMARY KEY REFERENCES CX_FRAMEWORK_EXECUTIONS(EXECUTION_ID), PROFILE_ID VARCHAR(128) NOT NULL REFERENCES CX_LLM_PROVIDER_PROFILES(PROFILE_ID), PROFILE_VERSION INTEGER NOT NULL CHECK(PROFILE_VERSION>0), PERMISSION_VERSION INTEGER NOT NULL CHECK(PERMISSION_VERSION>0), TARGET_ID VARCHAR(128) NOT NULL REFERENCES CX_DEPLOYMENT_TARGETS(TARGET_ID), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
    "CX_RUNTIME_DERIVATIONS": {
        "columns": ["EXECUTION_ID", "DERIVATION_ID", "CREATED_AT"],
        "immutable_columns": ["EXECUTION_ID", "DERIVATION_ID", "CREATED_AT"],
        "definition": "EXECUTION_ID VARCHAR(128) PRIMARY KEY REFERENCES CX_RUNTIME_CONTEXT_BINDINGS(EXECUTION_ID), DERIVATION_ID VARCHAR(128) NOT NULL UNIQUE REFERENCES CX_CONTEXT_DERIVATIONS(DERIVATION_ID), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
    },
    "CX_FRAMEWORK_REQUESTS": {
        "columns": ["ACTOR_ID", "IDEMPOTENCY_KEY", "REQUEST_DIGEST", "EXECUTION_ID", "CREATED_AT"],
        "immutable_columns": ["ACTOR_ID", "IDEMPOTENCY_KEY", "REQUEST_DIGEST", "EXECUTION_ID", "CREATED_AT"],
        "definition": "ACTOR_ID VARCHAR(128) NOT NULL REFERENCES CX_PRINCIPALS(PRINCIPAL_ID), IDEMPOTENCY_KEY VARCHAR(128) NOT NULL, REQUEST_DIGEST VARCHAR(64) NOT NULL, EXECUTION_ID VARCHAR(128) NOT NULL UNIQUE REFERENCES CX_FRAMEWORK_EXECUTIONS(EXECUTION_ID), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(ACTOR_ID,IDEMPOTENCY_KEY)",
    },
}


def schema_statements():
    return ["CREATE TABLE " + name + " (" + table["definition"] + ")" for name, table in TABLES.items()]
